# Generated by Django 3.2 on 2021-05-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=500)),
                ('movie_id', models.IntegerField()),
                ('release_date', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
